### ISSUE TITLE
issue with js2py library

### ISSUE THREAD

**Issue by vstri** [HiddenCodeDevs/BlumTelegramBot#14]
Installed everything by guide, filled app access(api_id and api_hash)
but after executing the command: python main.py I've faced with issue:
Traceback (most recent call last):
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\tapper.py", line 9, in <module>
    from aiocfscrape import CloudflareScraper
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\venv\Lib\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\venv\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\venv\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\venv\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\venv\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3


System: Windows
Python version: Python 3.12.5

**Comment by MrTimonM** [comment]
bro, uninstall python and install 3.10

**Comment by vstri** [comment]
Helped. Thanks
