### ISSUE TITLE
Error occurred during friend balance: Server disconnected

### ISSUE THREAD

**Issue by AlexArGC** [HiddenCodeDevs/BlumTelegramBot#19]
Почему-то при нескольких аккаунтов поднимается нормально только часть, причем например первые 9 штук. А остальные висят и не авторизуются. А потом сыпет такими ошибками.

У CloudflareScraper какие то ограничения есть?

```python
2024-09-06 16:02:26 | ERROR | 10 Oksana-1 | Error occurred during friend balance: Server disconnected
2024-09-06 16:02:26 | ERROR | 10 Oksana-1 | Unknown error: cannot unpack non-iterable NoneType object
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Python\Python311\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение
2024-09-06 16:16:58 | ERROR | 10 Oksana-1 | Error occurred during friend balance: Server disconnected
2024-09-06 16:16:58 | ERROR | 10 Oksana-1 | Unknown error: cannot unpack non-iterable NoneType object
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Python\Python311\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

```

**Comment by AlexKrutoy** [comment]
прокси плохие

**Comment by AlexArGC** [comment]
> прокси плохие

Сомнительно, это происходит даже на прямых коннектах... У меня есть 3 акка через свой IP.

**Comment by AlexArGC** [comment]
Ошибка была вызвана "зависанием" авторизации в цикле. Т.к. у некуторых аккаунтов ТГ было пустое имя usrename.
Самое правильное решение просто дать ему имя. Как предложение при регистрации сессий проверять есть ли имя username, и добавлять если нету:

```python
 # Создаем клиент Pyrogram
   with Client("my_account", api_id=api_id, api_hash=api_hash) as app:
       try:
           # Пытаемся установить новое имя пользователя
           result = app.update_username(new_username)
           if result:
               print(f"Username успешно изменен на {new_username}")
           else:
               print("Не удалось изменить username. Возможно, это имя уже занято.")
       except Exception as e:
           print(f"Произошла ошибка: {e}")
```
