### ISSUE TITLE
ERROR | Can`t get new token, trying again

### ISSUE THREAD

**Issue by devrabie** [HiddenCodeDevs/BlumTelegramBot#73]
INFO | @abdakrim1 | Bot will start in 23s
2024-11-02 18:07:08 | SUCCESS | User agent saved successfully
2024-11-02 18:07:08 | WARNING | @abdakrim1 | Proxy not installed! This may lead to account ban! Be careful.
2024-11-02 18:07:09 | INFO | @abdakrim1 | Try register using ref - QwD3tLsY8f and nickname - abdakrim1mjbe
2024-11-02 18:07:09 | ERROR | @abdakrim1 | Can`t get new token, trying again
2024-11-02 18:07:09 | INFO | @abdakrim1 | Account login successfully
Traceback (most recent call last):
  File "/root/BlumTelegramBot/main.py", line 40, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete    return future.result()
  File "/root/BlumTelegramBot/main.py", line 35, in main
    await actions[action]()
  File "/root/BlumTelegramBot/bot/utils/launcher.py", line 87, in run_tasks
    await asyncio.gather(*tasks)
  File "/root/BlumTelegramBot/bot/core/tapper.py", line 399, in run_tapper
    await Tapper(tg_client=tg_client, loop=loop).run(proxy=proxy)
  File "/root/BlumTelegramBot/bot/core/tapper.py", line 380, in run
    await self.check_daily_reward()
  File "/root/BlumTelegramBot/bot/core/tapper.py", line 302, in check_daily_reward
    daily_reward = await self._api.daily_reward_is_available()
  File "/root/BlumTelegramBot/bot/core/api.py", line 34, in wrapper
    return await method(self, *arg, **kwargs)
  File "/root/BlumTelegramBot/bot/core/api.py", line 79, in daily_reward_is_available
    raise BaseException(f"need update daily_reward_is_available. response: {data}")
BaseException: need update daily_reward_is_available. response: {'message': 'Invalid jwt token'}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/BlumTelegramBot/main.py", line 44, in <module>
    raise BaseException
BaseException
Exception ignored in: <function Tapper.__del__ at 0x7f56b4feb5b0>
Traceback (most recent call last):
  File "/root/BlumTelegramBot/bot/core/tapper.py", line 55, in __del__
  File "/usr/lib/python3.10/asyncio/base_events.py", line 436, in create_task
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
Unclosed client session
client_session: <aiocfscrape.CloudflareScraper object at 0x7f56b6661ba0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f56b4f02920>, 6845158.458010264)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7f56b4f02ce0>, 6845158.664982746)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f56b4fe3070>

**Comment by ArthurKoba** [comment]
Fixed in #74
