### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by Masiromem** [HiddenCodeDevs/BlumTelegramBot#75]
Привет Админ, подскажите пожалуйста в чем проблема, до обновление с прокси не было проблем:

Traceback (most recent call last):
  File "/root/BlumTelegramBot/bot/utils/checkers.py", line 8, in check_proxy
    response = await http_client.get(url='https://api.ipify.org?format=json', timeout=ClientTimeout(5))
  File "/root/BlumTelegramBot/venv/lib/python3.10/site-packages/aiocfscrape/__init__.py", line 79, in _request
    resp = await super()._request(method, url, *args, **kwargs)
  File "/root/BlumTelegramBot/venv/lib/python3.10/site-packages/aiohttp/client.py", line 663, in _request
    conn = await self._connector.connect(
  File "/root/BlumTelegramBot/venv/lib/python3.10/site-packages/aiohttp_proxy/connector.py", line 100, in connect
    return await super(ProxyConnector, self).connect(
  File "/root/BlumTelegramBot/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 563, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/BlumTelegramBot/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1032, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/root/BlumTelegramBot/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/root/BlumTelegramBot/venv/lib/python3.10/site-packages/aiohttp_proxy/connector.py", line 85, in _wrap_create_connection
    await sock.connect((host, port))
  File "/root/BlumTelegramBot/venv/lib/python3.10/site-packages/aiohttp_proxy/proto.py", line 156, in connect
    await self.negotiate()
  File "/root/BlumTelegramBot/venv/lib/python3.10/site-packages/aiohttp_proxy/proto.py", line 370, in negotiate
    await self._socks_connect()
  File "/root/BlumTelegramBot/venv/lib/python3.10/site-packages/aiohttp_proxy/proto.py", line 295, in _socks_connect
    req_addr, resolved_addr = await self._build_dest_address()
  File "/root/BlumTelegramBot/venv/lib/python3.10/site-packages/aiohttp_proxy/proto.py", line 319, in _build_dest_address
    port_bytes = struct.pack(">H", port)
struct.error: required argument is not an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/BlumTelegramBot/main.py", line 40, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/BlumTelegramBot/main.py", line 35, in main
    await actions[action]()
  File "/root/BlumTelegramBot/bot/utils/launcher.py", line 80, in run_tasks
    await asyncio.gather(*tasks)
  File "/root/BlumTelegramBot/bot/core/tapper.py", line 288, in run_tapper
    await Tapper(tg_client, session_logger).run(proxy=proxy)
  File "/root/BlumTelegramBot/bot/core/tapper.py", line 249, in run
    ip = await check_proxy(session)
  File "/root/BlumTelegramBot/bot/utils/checkers.py", line 15, in check_proxy
    logger.error(f"Proxy check error {e.__name__}: {e}")
AttributeError: 'error' object has no attribute '__name__'. Did you mean: '__ne__'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/BlumTelegramBot/main.py", line 44, in <module>
    raise BaseException
BaseException

**Comment by ArthurKoba** [comment]
Я не уверен что у вас обновлен бот. 

`logger.error(f"Proxy check error {e.name}: {e}")` - указывает на то, что у вас другой код. В текущем состоянии у бота код следующий `logger.error(f"Proxy check error {e.__name__}: {e}")` и он работает исправно.
