### ISSUE TITLE
Stop Tapper. Reason: error auth_with_web_data

### ISSUE THREAD

**Issue by vstri** [HiddenCodeDevs/BlumTelegramBot#77]
2024-11-04 12:56:11 | ERROR | BSIB | Traceback (most recent call last):
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\tapper.py", line 260, in run
    await self.auth(session)
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\tapper.py", line 42, in auth
    await self._api.login(web_data_params=web_data_params)
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 88, in login
    data = await self.auth_with_web_data(auth_web_data)
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 74, in auth_with_web_data
    raise Exception(f"error auth_with_web_data. resp[{resp.status}]: {resp_json}")
Exception: error auth_with_web_data. resp[409]: {'message': 'Username is not available'}

2024-11-04 12:56:11 | CRITICAL | BSIB | Stop Tapper. Reason: error auth_with_web_data. resp[409]: {'message': 'Username is not available'}

NOTE: The account has the username

**Comment by ArthurKoba** [comment]
Fixed
