### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by vstri** [HiddenCodeDevs/BlumTelegramBot#78]
2024-11-05 13:05:57 | ERROR | PGB | Traceback (most recent call last):
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 34, in wrapper
    return await method(self, *arg, **kwargs)
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 134, in daily_reward_is_available
    resp = await self.get(f"{self.game_url}/api/v1/daily-reward?offset=-180")
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 50, in get
    raise NeedRefreshTokenError()
bot.exceptions.api.NeedRefreshTokenError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 34, in wrapper
    return await method(self, *arg, **kwargs)
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 134, in daily_reward_is_available
    resp = await self.get(f"{self.game_url}/api/v1/daily-reward?offset=-180")
AttributeError: 'coroutine' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\tapper.py", line 282, in run
    await self.check_daily_reward()
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\tapper.py", line 196, in check_daily_reward
    daily_reward = await self._api.daily_reward_is_available()
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 37, in wrapper
    return await wrapper(method(self, *arg, **kwargs))
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 41, in wrapper
    self._log.error(f"Error on BlumApi.{method.__name__} | {type(e).__name__}: {e}")
AttributeError: 'coroutine' object has no attribute '_log'

2024-11-05 13:05:57 | ERROR | PGB | Unhandled error2024-11-05 13:05:57 | ERROR | PGB | Traceback (most recent call last):
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 34, in wrapper
    return await method(self, *arg, **kwargs)
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 134, in daily_reward_is_available
    resp = await self.get(f"{self.game_url}/api/v1/daily-reward?offset=-180")
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 50, in get
    raise NeedRefreshTokenError()
bot.exceptions.api.NeedRefreshTokenError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 34, in wrapper
    return await method(self, *arg, **kwargs)
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 134, in daily_reward_is_available
    resp = await self.get(f"{self.game_url}/api/v1/daily-reward?offset=-180")
AttributeError: 'coroutine' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\tapper.py", line 282, in run
    await self.check_daily_reward()
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\tapper.py", line 196, in check_daily_reward
    daily_reward = await self._api.daily_reward_is_available()
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 37, in wrapper
    return await wrapper(method(self, *arg, **kwargs))
  File "C:\Users\strel\OneDrive\Рабочий стол\HiddenCodeDevsBlum\BlumTelegramBot\bot\core\api.py", line 41, in wrapper
    self._log.error(f"Error on BlumApi.{method.__name__} | {type(e).__name__}: {e}")
AttributeError: 'coroutine' object has no attribute '_log'

2024-11-05 13:05:57 | ERROR | PGB | Unhandled error

**Comment by ArthurKoba** [comment]
already fixed
