### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by dogbes1** [HiddenCodeDevs/BlumTelegramBot#89]
after python3 main.py i got this errors ,what should i do?
Traceback (most recent call last):
  File "C:\Users\Дмитрий\Desktop\BlumTelegramBot-main\main.py", line 5, in <module>
    from bot.core.registrator import register_sessions
  File "C:\Users\Дмитрий\Desktop\BlumTelegramBot-main\bot\core\registrator.py", line 4, in <module>
    from bot.utils.logger import logger
  File "C:\Users\Дмитрий\Desktop\BlumTelegramBot-main\bot\utils\__init__.py", line 1, in <module>
    from . import launcher
  File "C:\Users\Дмитрий\Desktop\BlumTelegramBot-main\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\Дмитрий\Desktop\BlumTelegramBot-main\bot\core\tapper.py", line 6, in <module>
    import aiocfscrape
  File "C:\Users\Дмитрий\Desktop\BlumTelegramBot-main\venv\Lib\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "C:\Users\Дмитрий\Desktop\BlumTelegramBot-main\venv\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\Дмитрий\Desktop\BlumTelegramBot-main\venv\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\Дмитрий\Desktop\BlumTelegramBot-main\venv\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дмитрий\Desktop\BlumTelegramBot-main\venv\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Дмитрий\Desktop\BlumTelegramBot-main\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дмитрий\Desktop\BlumTelegramBot-main\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

**Comment by SQDYsll** [comment]
Yes, i'm also have this problem at startup

upd. Their telegram channel says - reinstall Python and check the box when installing "add to Path". I did it 3 times, it didn't help😢
